apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
    app: httpd
    spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    app: httpd
  template:
    metadata:
      labels:
      matchLabels:
       app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "700m"
    ports:
      - containerPort: 80