apiVersion: v1
kind: Pod
metadata:
  name: 01-sample
  labels:
    app: samtos
spec:
  containers:
  - name: sample 
    image: centos
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    resources:
      requests:
          memory: "64Mi"
          cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "700m"