apiVersion: v1
kind: Pod
metadata:
  name: 01-webserver
  labels:
    app: weberver
spec:
  containers:
  - name: webserver 
    image: httpd
       resources:
      requests:
          memory: "64Mi"
          cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "300m"

    ports:
      - containerPort: 80
