---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    name: web
spec:
  containers:
  - name: web
    image: httpd
    resources:
      requests:
        memory: "64Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "700m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service-int
spec:
  selector:
    name: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
