---
apiVersion: v1
kind: Pod
metadata:
  name: stack-tomcat
  labels:
    app: tomcat
spec:
  containers:
  - name: tomcat 
    image: rkalluru/b39-stack-tomcat:v1

    resources:
      requests:
        memory: "64Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "700m"
    ports:
      - containerPort: 8080
  ---
apiVersion: v1
kind: Service
metadata:
  name: stack-httpd-ext
spec:
  type: LoadBalancer
  selector:
    name: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80