---
apiVersion: v1
kind: Pod
metadata:
  name: stack-mariadb
  labels:
    app: db
spec:
  containers:
  - name: tomcat 
    image: mariadb
    env:
      - name: MYSQL_ROOT_PASSWORD
          value: root
    resources:
      requests:
        memory: "64Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "700m"
    ports:
      - containerPort: 3306