---
apiVersion: v1
kind: Secret
metadata:
   name: db-root-cred
 type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-disk
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow

---
apiVersion: v1
kind: Pod
metadata:
  name: stack-mariadb
  labels:
    app: db
spec:
  containers:
  - name: tomcat 
    image: mariadb
    env:
      - name: MYSQL_ROOT_PASSWORD
          valueFrom:
          secretKeyRef:
            name: db-root-cred
            key: MYSQL_ROOT_PASSWORD
    volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: mariadb-disk
     
    resources:
      requests:
        memory: "64Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "700m"
    ports:
      - containerPort: 3306
    
  volumes:
    - name: mariadb-disk
      persistentVolumeClaim:
        claimName: mariadb-disk