---
apiVersion: v1
kind: Pod
metadata:
  name: stack-httpd
  labels:
    app: httpd
spec:
  containers:
  - name: webserver 
    image: rkalluru/b39-stack-httpd

    resources:
      requests:
        memory: "64Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "700m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service-ext
spec:
  type: LoadBalancer
  selector:
    name: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80